name: ci

on:
    pull_request:
        branches:
            - canary
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Prepare .env file
        run: |
            cp .env.production.example .env.production

      - name: Build Docker image using custom script
        run: |
            chmod +x ./docker/build.sh
            ./docker/build.sh ${{ github.ref_name == 'canary' && 'canary' || '' }}